# -*- coding: utf-8 -*-
"""Entrga_1_Modelos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MIkimFJrPa4mRsSzmB-dzUP4qAtzuOw0
"""

import pandas as pd

!unzip train.zip

#Cargar archivos
p= pd.read_csv('train.csv')

p.head()

#Informacion General
p.info()

#Estadisticas basicas
p.describe()

print(p["E_PRGM_DEPARTAMENTO"].value_counts())

print (df["F_ESTRATOVIVIENDA"].value_counts())

for col in p.columns:
    if df[col].dtype == "object":
        print(f"\nDistribución de valores en la columna '{col}':")
        print(df[col].value_counts().head(10))